# Generated by Django 2.0.5 on 2018-07-27 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fruitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='each_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=2048)),
                ('cityname', models.CharField(max_length=128, null=True)),
                ('pincode', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rateandreview',
            name='rating',
        ),
        migrations.AlterField(
            model_name='checkouts',
            name='appartment',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='checkouts',
            name='cityname',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='checkouts',
            name='houseno',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='each_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitapp.Order'),
        ),
        migrations.AddField(
            model_name='each_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitapp.Product'),
        ),
    ]
