# Generated by Django 2.0.5 on 2018-07-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0002_auto_20180727_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateandreview',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4),
        ),
    ]
